# Generated by Django 5.1.1 on 2024-09-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_formmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormModel',
            new_name='FormData',
        ),
    ]
